### ISSUE TITLE
ALIVE

### ISSUE THREAD

**Issue by gjkaur** [NabJa/deep-brats#1]
Could not convert 2896164647884652695031278115551542149569835916936843948628755576350332331232033361063246617048847312833389172308422928672649587121031820866052240726585597239610208355152385453159237613371257961438718013937517671684383453941141915038758734448401ALIVE (361 days later)99651010204362962781462001527117835356211227182277155114878580114577427409112412334746846131425384162405243197303363425036881410374117692120150300630330728540558322630370864301102094481992916008046341561268822355148982187394812737362677126242432910417311276161118283174056211753577479461034688246742522382128232763544829662637212147633330232434995213244145877508823465192541471531076802509036151051293260109675935154431188018419730045654062633437442145 to numeric

**Comment by NabJa** [comment]
In the kaggle data there is one outlier in the _Survival_days_ column.
You can run [preprocess_kaggle_data](https://github.com/NabJa/deep-brats/blob/d8f4fb6fdfbc565eff4d2bc7a45d1cf652694f57/uncertainty/data_generator/data.py#L17) to fix it.
